AllCops:
  NewCops: enable
  SuggestExtensions: false

Security/JSONLoad:
  Exclude:
    - 'app/models/common.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

StringLiterals:
  Exclude:
    - 'db/schema.rb'
    - 'config/schedule.rb'

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstHashElementIndentation:
  Exclude:
    - 'app/controllers/callbacks_controller.rb'
    - 'app/models/user.rb'
    - 'config/deploy.rb'

Layout/HashAlignment:
  Enabled: false

Lint/EmptyFile:
  Exclude:
    - 'config/deploy/production.rb'

Metrics/AbcSize:
  Max: 161

Metrics/BlockLength:
  Max: 198

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 283

Metrics/CyclomaticComplexity:
  Max: 31

Metrics/MethodLength:
  Max: 80

Metrics/PerceivedComplexity:
  Max: 29

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/api/v1/users_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'bin/bundle'

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 6

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 5

Layout/LineLength:
  Max: 200
  Exclude:
    - 'db/seeds/01_category.rb'
    - 'db/seeds/02_items.rb'

Style/GuardClause:
  Exclude:
    - 'app/models/user.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - 'config/application.rb'
