development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yandex_auth_app_id: <%= ENV["YA_AUTH_APP_ID"] %>
  yandex_auth_secret: <%= ENV["YA_AUTH_SECRET"] %>
  telegram:
    bot:
      token: <%= ENV["BOT_TOKEN"] %>
      username: <%= ENV["BOT_NAME"] %>
#      server: http://local.bot.api.server

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yandex_auth_app_id: <%= ENV["YA_AUTH_APP_ID"] %>
  yandex_auth_secret: <%= ENV["YA_AUTH_SECRET"] %>
  telegram:
    bot:
      token: <%= ENV["BOT_TOKEN"] %>
      username: <%= ENV["BOT_NAME"] %>
